### PR TITLE
Minor gitignore stuff [v2]

### PR DESCRIPTION
**Pull request by democat3457**
wack but ok

### CODE REVIEW

**Comment by democat3457** [comment]
Also not sure why the change itlt commit isn't showing

**Comment by democat3457** [comment]
weird, apparently the itlt commit wasnt transferred over
ill cherry-pick it

**Comment by kil0byt3** [comment]
GitHub is weird. I’ll review first thing tom and merge. Thanks again. You’re a hero

**Comment by democat3457** [comment]
and its still broken... sigh

**Comment by democat3457** [comment]
O I know why the multitude of files aren't showing up... the gitignore is preventing those changes from being transferred across forks. However, the commit still isn't showing up.

**Comment by democat3457** [comment]
and there we go
the files changed tab is very broken right now but it should work
I changed the branching commit from the itlt commit to the one before it

**Comment by kil0byt3** [comment]
thanks for figuring that out 🥇

**Pull request merged**
