### PR TITLE
Change itlt to 2.77.2

### PR DESCRIPTION
**Pull request by democat3457**
Also do some random things the game decided to fix (like removing cyclicmagic from some files)

### CODE REVIEW

**Comment by kil0byt3** [comment]
Thanks mate!!

**Comment by kil0byt3** [comment]
Also, wait, middle click in inventory is intended. Other than that it's good

**Comment by kil0byt3** [comment]
Can you rem that one change and then I'll merge

**Comment by democat3457** [comment]
o ok

**Comment by democat3457** [comment]
imma make a new pr since this one is borked bc of the merge

**Pull request merged**
