### PR TITLE
Blacklist light/dark edge

### PR DESCRIPTION
**Pull request by democat3457**

### CODE REVIEW

**Comment by CalaMariGold** [comment]
Item blacklist does not work. Check eplus GH issues

**Comment by democat3457** [comment]
yea i made note in this commit af79ee3cddaffdc6009f51afd6bdd6a79f100fa6

**Comment by democat3457** [comment]
also imma link #313

**Comment by CalaMariGold** [comment]
Closing, I'll do this myself once the bug is fixed

**Comment by democat3457** [comment]
Sounds good.

**Pull request closed without merging**
