### PR TITLE
made toolbelt reforgeable with leather

### PR DESCRIPTION
**Pull request by Eksekk**

### CODE REVIEW

**Comment by Eksekk** [comment]
why this was closed?

**Comment by democat3457** [comment]
Because toolbelt isn't even supposed to have qualities in the first place.

**Comment by democat3457** [comment]
It was added to the blacklist here 0b8c98321448bfcfe3521275a46fe05d4ad6ff0f and, seeing no more need for this PR, closed it.

**Comment by Eksekk** [comment]
And why is it not supposed to have qualities?

**Comment by democat3457** [comment]
Screen Shot 2020-05-19 at 2 06 16 PM

**Comment by Eksekk** [comment]
NBT tags don't work that if you add any new tags you replace existing ones, they are a system DESIGNED to work with many tags from different sources. No reason to be afraid here.

**Comment by Eksekk** [comment]
Also, quick search in RLCraft discord (which uses both toolbelt and quality tools) didn't show any reports of people losing things in their belt when reforging.

**Comment by Eksekk** [comment]
And a quick ingame (RotN) test showed that things in belt are exactly the same after reforging.

**Comment by democat3457** [comment]
Alrighty then.

**Pull request merged**
