### PR TITLE
Underground Biomes made compatible with FutureMC's Blast Furnace

### PR DESCRIPTION
**Pull request by Spencer92**
I tested all the recipes and there weren't any problems on my end.

### CODE REVIEW

**Comment by CalaMariGold** [comment]
Is it possible to get modded ores to work?

**Comment by Spencer92** [comment]
What nodded ores did you have in mind?

If you're talking about Rubies, Sapphires Peridot, and the like, then those
have been already added, if you're talking about stuff outside of
underground biomes, then I can. Main issue is time.

**Comment by Spencer92** [comment]
Actually it seems like there isn't much ores left to be done, so I'll reupload.

**Comment by CalaMariGold** [comment]
Keep in mind there are no UGB ores. All ores become the default ore.

**Comment by Spencer92** [comment]
It doesn't become the default ore if you use Silk Touch. Probably a fairly niche usecase, but it's there.

**Comment by Spencer92** [comment]
But that was an error on my part about going to default. I don't think I'll be able to fix it by tonight.

**Comment by CalaMariGold** [comment]
all good, we'll have it in the next update (2.75)

**Pull request closed without merging**
