### PR TITLE
Fix wack personalities

### LINKED ISSUE #294: [CRASH] Multiple mini-crashes with Living Enchant
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
VanillaFix reports several small crashes quite frequently when using the True Dark's Edge against random mobs.

**To Reproduce**
Slay random entities with the True Dark's Edge (and, I expect, the True Light's Edge)

**Crash Log**
`---- Minecraft Crash Report ----
// Don't do that.

Time: 2020-04-28 01:03:37 EDT
Description: Error executing task

**Crash 1**
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 0
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
    at com.clownvin.livingenchantment.personality.Personality.getRandomPhrase(Personality.java:129)
    at com.clownvin.livingenchantment.personality.Personality.getOnTargetHurt(Personality.java:141)
    at com.clownvin.livingenchantment.LivingEnchantment.doTalking(LivingEnchantment.java:211)
    at com.clownvin.livingenchantment.LivingEnchantment.onLivingHurt(LivingEnchantment.java:448)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_420_LivingEnchantment_onLivingHurt_LivingHurtEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:604)
    at net.minecraft.entity.EntityLivingBase.damageEntity(EntityLivingBase.java:1410)
    at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:926)
    at net.daveyx0.primitivemobs.entity.passive.EntityGroveSprite.attackEntityFrom(EntityGroveSprite.java:257)
    at net.minecraft.entity.player.EntityPlayer.attackTargetEntityWithCurrentItem(EntityPlayer.java:1328)
    at net.minecraft.entity.player.EntityPlayerMP.attackTargetEntityWithCurrentItem(EntityPlayerMP.java:1425)
    at com.tmtravlr.potioncore.network.PacketHandlerServer.useEntity(PacketHandlerServer.java:113)
    at com.tmtravlr.potioncore.network.PacketHandlerServer.lambda$onMessage$1(PacketHandlerServer.java:66)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more`

**Crash 2**
`---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2020-04-27 21:20:45 EDT
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 0
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
    at com.clownvin.livingenchantment.personality.Personality.getRandomPhrase(Personality.java:129)
    at com.clownvin.livingenchantment.personality.Personality.getOnKill(Personality.java:149)
    at com.clownvin.livingenchantment.LivingEnchantment.doTalking(LivingEnchantment.java:205)
    at com.clownvin.livingenchantment.LivingEnchantment.onLivingKilled(LivingEnchantment.java:425)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_423_LivingEnchantment_onLivingKilled_LivingDeathEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:615)
    at net.minecraft.entity.EntityLivingBase.onDeath(EntityLivingBase.java:1168)
    at net.minecraft.entity.monster.EntityZombie.onDeath(EntityZombie.java:546)
    at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:1023)
    at net.minecraft.entity.monster.EntityMob.attackEntityFrom(EntityMob.java:70)
    at net.minecraft.entity.monster.EntityZombie.attackEntityFrom(EntityZombie.java:233)
    at net.minecraft.entity.player.EntityPlayer.attackTargetEntityWithCurrentItem(EntityPlayer.java:1328)
    at net.minecraft.entity.player.EntityPlayerMP.attackTargetEntityWithCurrentItem(EntityPlayerMP.java:1425)
    at com.exidex.stg.LeftClickEventHandler.onLeftClick(LeftClickEventHandler.java:57)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_697_LeftClickEventHandler_onLeftClick_LeftClickBlock.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1130)
    at net.minecraft.server.management.PlayerInteractionManager.onBlockClicked(PlayerInteractionManager.java:141)
    at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:693)
    at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:40)
    at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:10)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more
`

**Info (please complete the following information):**
 - Modpack Version: 2.78
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.78

### PR DESCRIPTION
**Pull request by democat3457**
Fix #294 also I didn't resolve some conflicts :eyes: lemme fix those first

### CODE REVIEW

**Comment by democat3457** [comment]
Conflicts have been resolved

**Comment by CalaMariGold** [comment]
Can you fix the other conflicts please?

**Comment by democat3457** [comment]
:/

**Comment by democat3457** [comment]
Fixed

**Comment by CalaMariGold** [comment]
Your clean directory commit removed many key files. And it's not letting me revert it...

**Comment by democat3457** [comment]
They were key? I thought they were auto generated...

**Comment by democat3457** [comment]
Especially since they were already in the .gitignore

**Comment by CalaMariGold** [comment]
Default options and JEIHider to name 2

**Comment by CalaMariGold** [comment]
ActualMusic config too

**Comment by democat3457** [comment]
Screen Shot 2020-05-10 at 10 37 59 PM
Most of that stuff was added by you in the .gitignore

**Comment by CalaMariGold** [comment]
Yes because we don't need to update it anymore, but it still needs to be present lmao. They're config files we've edited in the past

**Comment by democat3457** [comment]
O

**Comment by democat3457** [comment]
Is the multimob/mobinformation needed, and is the config/fantasticlib/reference needed?

**Comment by CalaMariGold** [comment]
no, i fixed it

**Comment by democat3457** [comment]
😭 sorry

**Comment by democat3457** [comment]
can we at least do `git rm --cached config/fantasticlib/*` and `git rm --cached config/multimob/modInformation/*` across all devs so they don't get committed and cause useless merge conflicts?

**Pull request merged**
