### PR TITLE
OVERHAUL JEI DESCRIPTION STYLE

### PR DESCRIPTION
**Pull request by democat3457**
Actually add order to jei_descriptions
In the branch rebase I may have accidentally overlooked some new descriptions, sorry :(

### CODE REVIEW

**Comment by CalaMariGold** [comment]
`I may have accidentally overlooked some new descriptions`

What do you mean? Are all the descriptions in there? We won't merge it if you accidentally removed some

**Comment by democat3457** [comment]
They should all be in there from the conflict, but the resolution of the conflict might have reverted some edits from the commits after the original commit. (I made the description rework a long time ago but hadn't committed it so many conflicts ended up.)

**Comment by democat3457** [comment]
By reverted edits, I mean mainly typo fixes

**Comment by kil0byt3** [comment]
I'm going to take what you did and manually implement to make sure I got it all, move a few things around, and also check for typos. Thanks for making a beautiful style guide, you magnificent bastard <3

**Pull request closed without merging**
