### PR TITLE
Fix Spartan Fire Myrmex weapons not dealing damage bonus

### LINKED ISSUE #259: [BUG] Spartan myrmex weapons deal incorrect damage
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Description**
All of the weapons made of both types of myrmex chitin from the spartanfire mod(ex: desert myrmex longsword, jungle myrmex throwing knife) deal an incorrect amount of damage on hit/throw. The damage bonus upon hitting non-arthropod mobs is supposed to be 4, and this can be confirmed by hitting anything with a myrmex weapon that does less than 4 base damage or by looking at the description for the myrmex sword. Thus, i would expect 4 to be added to my damage when hitting a non-arthropod mob, however this does not happen as it seems to take the higher of the 2 numbers 4 and the base damage rather than adding them.

**To Reproduce**
Steps to reproduce the behavior:Take any myrmex weapon from the spartanfire mod and test damage compared to a myrmex sword on an arthropod and a non arthropod. Also test dagger and throwables and observe them deal 4 damage.

**Expected behavior**
The damage bonus is expected to be added to the weapon damage rather than be a minimum.

**Screenshots**
image
image

image
image
image

**Info (please complete the following information):**
 - Modpack Version: 2.77
 - Server or Singleplayer:Both
 - Version the world was created on:2.77

**Additional context**
I think the mod may be taking max(basedmg,4) instead of basedamage+4

### PR DESCRIPTION
**Pull request by democat3457**
I've recompiled the spartanfire mod with a reworked damage bonus that has been tested and works. I've also adjusted the tooltips slightly to be more descriptive about the damage bonus. (The spartanfire mod has an MIT license and it hasn't been updated in 6 months :/ so an issue probably wouldn't do much good.) Should fix #259

### CODE REVIEW

**Comment by CalaMariGold** [comment]
You need to upload it to CurseForge.

**Comment by democat3457** [comment]
https://www.curseforge.com/minecraft/mc-mods/spartan-and-fire-hotfix Uploaded and approved.

**Comment by kil0byt3** [comment]
Thanks so much!

**Comment by kil0byt3** [comment]
I do see some comments on Curse from the original creators. Maybe it's better to make a pull request for their mod, and have your changes committed in to the original mod?

**Comment by democat3457** [comment]
Oops it appears the dev is actually active -.- sorry for confusing y'all.

**Comment by kil0byt3** [comment]
No problem!

**Comment by democat3457** [comment]
Just a note, the hotfix was just merged into the actual Spartan and Fire mod.

**Pull request merged**
